name: CI - Semgrep
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
jobs:
  semgrep:
    name: Analyze (Semgrep)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #7.0.0
      - name: Run Semgrep analysis
        run: make ci-semgrep
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a
        with:
          sarif_file: semgrep.sarif
